debug: true
spring:
  application:
    name: media-uploader-service


  r2dbc:
    url: r2dbc:postgresql://localhost:5432/media_uploader
    username: postgres
    password: postgres

  data:
    r2dbc:
      repositories:
        enabled: true

  codec:
    max-in-memory-size: 500MB
  webflux:
    multipart:
      max-in-memory-size: 500MB
      max-parts: 10
      max-disk-usage-per-part: 500MB # the default value is -1, which means the disk size is the limit.
      max-headers-size: 10KB


  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8112/oauth2/jwks
          issuer-uri: http://localhost:8112


  liquibase:
    url: jdbc:postgresql://localhost:5432/media_uploader
    user: postgres
    password: postgres
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true



server:
  error:
    include-message: always
    include-exception: true
    include-binding-errors: always
    include-stacktrace: always
  port: 8088
  shutdown: graceful
logging:
  level:
    io.r2dbc.postgresql.QUERY: INFO
    com.mathias8dev: TRACE
  file:
    name: ./logs/local-${spring.application.name}.log

#springdoc: http://localhost:8080/webjars/swagger-ui/index.html#/
springdoc:
  swagger-ui:
    path: /swagger-ui.html

media-uploader:
  s3:
    accessKey: 1
    secretKey: 1
    bucketName: 1
  files-download-path: /api/data/files/download
  upload:
    dir: uploads


